version: "3"
services:
  sommelierr:
    image: ghcr.io/rare-magma/sommelierr:latest
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 64m
          pids: 16
